name: BuildAndDeploy

on:
  push:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile
        id: compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: |
            target/release/openorbiterwebsite
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH key for deploy
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYKEY }}
          known_hosts: ${{ secrets.DEPLOYHOSTS }}
      - name: Grab artifact
        uses: actions/download-artifact@v3
        with:
          name: Binary
      - name: Push built asset to server
        run: scp -P ${{ secrets.DEPLOYPORT }} openorbiterwebsite github-deployer@atlantis.orbiterforum.com:/srv/www/openorbiterwebsite
