name: BuildAndDeploy

on:
  push:
    branches:
      - main
      - landing_page

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile
        id: compile
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: true
          args: --release --target x86_64-unknown-linux-gnu
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Binary
          path: target/x86_64-unknown-linux-gnu/release/openorbiterwebsite
      - name: Set up SSH key for deploy
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOYKEY }}
          known_hosts: ${{ secrets.DEPLOYHOSTS }}
      - name: Push built asset to server
        run: scp -P 8777 target/x86_64-unknown-linux-gnu/release/openorbiterwebsite github-deployer@atlantis.orbiter-forum.com:/srv/www/openorbiterwebsite
